In [2]:
import nltk
import pandas as pd

In [3]:
nltk.download_shell()

NLTK Downloader
---------------------------------------------------------------------------
    d) Download   l) List    u) Update   c) Config   h) Help   q) Quit
---------------------------------------------------------------------------

Downloader>  q

In [4]:
messages = [line.rstrip() for line in open('/home/kmea/spam.csv',encoding='latin-1')]

In [5]:
print(len(messages))

5575

In [6]:
messages[0]

'v1,v2,,,'

In [7]:
for mess_no,message in enumerate(messages[:10]):
    print(mess_no,message)
print('\n')

0 v1,v2,,,
1 ham,"Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat...",,,
2 ham,Ok lar... Joking wif u oni...,,,
3 spam,Free entry in 2 a wkly comp to win FA Cup final tkts 21st May 2005. Text FA to 87121 to receive entry question(std txt rate)T&C's apply 08452810075over18's,,,
4 ham,U dun say so early hor... U c already then say...,,,
5 ham,"Nah I don't think he goes to usf, he lives around here though",,,
6 spam,"FreeMsg Hey there darling it's been 3 week's now and no word back! I'd like some fun you up for it still? Tb ok! XxX std chgs to send, å£1.50 to rcv",,,
7 ham,Even my brother is not like to speak with me. They treat me like aids patent.,,,
8 ham,As per your request 'Melle Melle (Oru Minnaminunginte Nurungu Vettam)' has been set as your callertune for all Callers. Press *9 to copy your friends Callertune,,,
9 spam,WINNER!! As a valued network customer you have been selected to receivea å£900 prize reward! To claim call 09061701461. Claim code KL341. Valid 12 hours only.,,,

In [8]:
messages[0]

'v1,v2,,,'

In [9]:
import pandas as pd

In [10]:
messages=pd.read_csv('/home/kmea/spam.csv',encoding='latin-1',usecols=['v1','v2'])

In [11]:
messages=messages.rename(columns={'v1':'label','v2':'message'})

In [12]:
messages.head()

  label                                            message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [13]:
import string

In [14]:
mess = "Sample message! Notice: it has punctuation."
string.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [15]:
nopunc = [c for c in mess if c not in string.punctuation]

In [16]:
nopunc

['S',
 'a',
 'm',
 'p',
 'l',
 'e',
 ' ',
 'm',
 'e',
 's',
 's',
 'a',
 'g',
 'e',
 ' ',
 'N',
 'o',
 't',
 'i',
 'c',
 'e',
 ' ',
 'i',
 't',
 ' ',
 'h',
 'a',
 's',
 ' ',
 'p',
 'u',
 'n',
 'c',
 't',
 'u',
 'a',
 't',
 'i',
 'o',
 'n']

In [17]:
nopunc = ''.join(nopunc)

In [18]:
nopunc

'Sample message Notice it has punctuation'

In [19]:
from nltk.corpus import stopwords

In [20]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /home/kmea/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [21]:
nopunc.split()

['Sample', 'message', 'Notice', 'it', 'has', 'punctuation']

In [22]:
clean_mess = [word for word in nopunc.split() if word.lower() not in
stopwords.words('english')]

In [23]:
clean_mess

['Sample', 'message', 'Notice', 'punctuation']

In [24]:
def text_process(mess):
    nopunc=[char for char in mess if char not in string.punctuation]
    nopunc="".join(nopunc)
    return[word for word in nopunc.split() if word.lower() not in
stopwords.words("english")]

In [25]:
messages.head()

  label                                            message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [26]:
messages['message'].head(5).apply(text_process)

0    [Go, jurong, point, crazy, Available, bugis, n...
1                       [Ok, lar, Joking, wif, u, oni]
2    [Free, entry, 2, wkly, comp, win, FA, Cup, fin...
3        [U, dun, say, early, hor, U, c, already, say]
4    [Nah, dont, think, goes, usf, lives, around, t...
Name: message, dtype: object

In [27]:
from sklearn.feature_extraction.text import CountVectorizer

In [28]:
bow_transformer=CountVectorizer(analyzer=text_process).fit(messages['message'])

In [29]:
print(len(bow_transformer.vocabulary_))

11304

In [30]:
mess4=messages['message'][6]

In [31]:
print(mess4)

Even my brother is not like to speak with me. They treat me like aids patent.

In [32]:
bow4=bow_transformer.transform([mess4])

In [33]:
print(bow4)

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 7 stored elements and shape (1, 11304)>
  Coords	Values
  (0, 1777)	1
  (0, 4512)	1
  (0, 5111)	1
  (0, 7698)	2
  (0, 8653)	1
  (0, 9860)	1
  (0, 10513)	1

In [34]:
bow_transformer.get_feature_names_out()[7800]

'lotta'

In [35]:
messages_bow=bow_transformer.transform(messages['message'])

In [36]:
print('shape of the Sparse Matrix:',messages['message'])

shape of the Sparse Matrix: 0       Go until jurong point, crazy.. Available only ...
1                           Ok lar... Joking wif u oni...
2       Free entry in 2 a wkly comp to win FA Cup fina...
3       U dun say so early hor... U c already then say...
4       Nah I don't think he goes to usf, he lives aro...
                              ...
5567    This is the 2nd time we have tried 2 contact u...
5568                Will Ì_ b going to esplanade fr home?
5569    Pity, * was in mood for that. So...any other s...
5570    The guy did some bitching but I acted like i'd...
5571                           Rofl. Its true to its name
Name: message, Length: 5572, dtype: object

In [37]:
messages_bow.nnz

50193

In [38]:
from sklearn.feature_extraction.text import TfidfTransformer

In [39]:
tfidf_transformer=TfidfTransformer().fit(messages_bow)

In [40]:
tfidf4=tfidf_transformer.transform(bow4)

In [41]:
print(tfidf4)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 7 stored elements and shape (1, 11304)>
  Coords	Values
  (0, 1777)	0.33521441416639297
  (0, 4512)	0.43692878744892083
  (0, 5111)	0.3383712690711893
  (0, 7698)	0.4149098236609654
  (0, 8653)	0.43692878744892083
  (0, 9860)	0.32680848361658965
  (0, 10513)	0.33521441416639297

In [42]:
messages_tfidf = tfidf_transformer.transform(messages_bow)

In [43]:
from sklearn.naive_bayes import MultinomialNB

In [44]:
spam_detect_model=MultinomialNB().fit(messages_tfidf,messages['label']
)

In [45]:
all_pred = spam_detect_model.predict(messages_tfidf)

In [46]:
all_pred

array(['ham', 'ham', 'spam', ..., 'ham', 'ham', 'ham'],
      shape=(5572,), dtype='<U4')

In [47]:
from sklearn.model_selection import train_test_split

In [48]:
msg_train,msg_test,label_train,label_test=train_test_split(messages['message'],messages['label'])

In [49]:
spam_detect_model=MultinomialNB().fit(messages_tfidf,messages['label']
)

In [50]:
predict = spam_detect_model.predict(messages_tfidf)

In [51]:
from sklearn.metrics import classification_report
print(classification_report(messages['label'],predict))

              precision    recall  f1-score   support

         ham       0.98      1.00      0.99      4825
        spam       1.00      0.85      0.92       747

    accuracy                           0.98      5572
   macro avg       0.99      0.92      0.95      5572
weighted avg       0.98      0.98      0.98      5572

In [52]:
from sklearn.model_selection import train_test_split
msg_train,msg_test,label_test,label_train = \
train_test_split(messages['message'],messages['label'],test_size=0.2)

In [53]:
from sklearn.pipeline import Pipeline
pipeline = Pipeline([('bow',CountVectorizer(analyzer=text_process)),('tfidf',TfidfTransformer()),('classifier',MultinomialNB()),])

In [54]:
pipeline.fit(msg_test,label_train)
predictions = pipeline.predict(msg_test)
print(classification_report(predictions,label_train))

              precision    recall  f1-score   support

         ham       1.00      0.96      0.98       997
        spam       0.74      1.00      0.85       118

    accuracy                           0.96      1115
   macro avg       0.87      0.98      0.92      1115
weighted avg       0.97      0.96      0.97      1115

In [56]:
from sklearn import model_selection,naive_bayes,svm
from sklearn.metrics import accuracy_score
pipeline1 = Pipeline([('bow',CountVectorizer(analyzer=text_process)),('tfidf',TfidfTransformer()),('classifier',svm.SVC(C=1.0,kernel='linear',degree=3,gamma='auto')),])
pipeline1.fit(msg_test,label_train)
predictions1 = pipeline1.predict(msg_test)
print(classification_report(predictions1,label_train))

              precision    recall  f1-score   support

         ham       1.00      1.00      1.00       958
        spam       0.98      0.99      0.99       157

    accuracy                           1.00      1115
   macro avg       0.99      1.00      0.99      1115
weighted avg       1.00      1.00      1.00      1115